LIBDIR := $(TOPDIR)/lib

#common *.c in src
LIB_COMMON_A := libCOMMON.a

#specific lib in base
LIB_XESAP_A := libxeSAP.a
LIB_XESOE_A := libxeSOE.a
LIB_XEAA_A := libxeAA.a
LIB_XECEO_A := libxeCEO.a
LIB_XESIS_A := libxeSIS.a
LIB_XESIS_F_A := libxeSIS_F.a
LIB_XESIS_E_A := libxeSIS_E.a
LIB_XEPM_A := libxePM.a
LIB_XEDAVINCI_A := libxeDavinci.a
LIB_XELOG_A := libxeLOG.a
LIB_XECONF_A := libxeCONF.a
LIB_XEOSD_A := libxeOSD.a
LIB_HXSDK_A	:= hxSDK.a
LIB_IPCAM_A	:= libIPCam.a
LIB_XEWDG_A:= libxeWDG.a
LIB_XEPTZ_A := libxePTZ.a
LIB_XEFPGA_A := libxefpga.a
LIB_XEAC51_A := libxeAC51.a
LIB_XEAC51_SO := libxeAC51.so
LIB_XELOG_SO := libxeLOG_REMOTE.so
LIB_XEDEX_A := libxeDEX.a
LIB_XEREC_A := libxeRecording.a

LIB_XECVA_A := libxeCVA.a
LIB_XECVA_PBPSP_A := libxeCVA_PBPSP.a

LIB_XECVA_BIN_SIMU_VENC_A := libxeCVA_BIN_Simu_VENC.a
LIB_XECVA_BIN_MUX_PS_A := libxeCVA_BIN_Mux_PS.a
LIB_XECVA_BIN_DEMUX_PS_A := libxeCVA_BIN_Demux_PS.a
LIB_XECVA_BIN_DEMUX_MP4V_A := libxeCVA_BIN_Demux_MP4V.a
LIB_XECVA_BIN_DEMUX_H264_A := libxeCVA_BIN_Demux_H264.a
LIB_XECVA_BIN_DISPLAY_V4L2_A := libxeCVA_BIN_Display_V4L2.a
LIB_XECVA_BIN_DM646X_CANVAS_A := libxeCVA_BIN_DM646x_Canvas.a
LIB_XECVA_BIN_OSD_A := libxeCVA_BIN_OSD.a
LIB_XECVA_BIN_CODEC_DVSDK_A := libxeCVA_BIN_Codec_DVSDK.a
LIB_XECVA_BIN_COLORBAR_A := libxeCVA_BIN_ColorBar.a
LIB_XECVA_BIN_DM646X_PCI_E_A := libxeCVA_BIN_DM646x_PCI_E.a
LIB_XECVA_BIN_DM646X_VPIF_E_A := libxeCVA_BIN_DM646x_VPIF_E.a
LIB_XECVA_BIN_AUDIO_PLAYBACK_A:=libxeCVA_BIN_audio_playback.a
LIB_XECVA_BIN_ALSA_PLAYBACK_A:=libxeCVA_BIN_alsa_playback.a
LIB_XECVA_BIN_DM646X_RESIZER_A:=libxeCVA_BIN_DM646x_Resizer.a
LIB_XECVA_EXT_DM646X_PCI_EXC_A:=libxeCVA_EXT_DM646x_PCI_Exc.a
LIB_XECVA_BIN_TVP5158_A:=libxeCVA_BIN_TVP5158.a
LIB_XEALGORITHM_A := libxealgorithm.a
LIB_DSPLINK_LIB := libxedsplink.lib
LIB_XECVA_BIN_DM646X_CCV_A := libxeCVA_BIN_DM646x_CCV.a
LIB_XECVA_BIN_DM646X_PCI2_F_A := libxeCVA_BIN_DM646x_PCI2_F.a
LIB_XECVA_BIN_DM368_RESIZER_A := libVA_BIN_DM368_Resizer.a
LIB_XECVA_BIN_CAPTURE_V4L2_A := libVA_BIN_Capture_V4L2.a
LIB_XECVA_BIN_Joint_4xD1_A := libVA_BIN_Joint_4xD1.a
LIB_XECVA_BIN_DM646X_GUI_A:=libxeCVA_BIN_DM646x_GUI.a
LIB_XECVA_BIN_CUTTER_PS_A :=libxeCVA_BIN_Cutter_PS.a
LIB_XECVA_BIN_CAPTURE_AUDIO_A :=libxeCVA_BIN_Capture_Audio.a
LIB_XECVA_BIN_CODEC_FFMPEG_A :=libxeCVA_BIN_Codec_FFMPEG.a
LIB_XECVA_BIN_EXCLUSIVE_ORDER_A := libxeCVA_BIN_Exclusive_Order.a

export LIBDIR LIB_COMMON_A LIB_XESAP_A LIB_XESOE_A LIB_XEAA_A LIB_XECEO_A \
		LIB_XESIS_A LIB_XESIS_F_A LIB_XESIS_E_A LIB_XEPM_A LIB_XEDAVINCI_A \
		LIB_XELOG_A LIB_XECONF_A LIB_XEOSD_A LIB_HXSDK_A LIB_XEWDG_A LIB_XEPTZ_A \
		LIB_XEFPGA_A LIB_XEAC51_A LIB_XELOG_SO LIB_XEAC51_SO LIB_XECVA_A LIB_XEDEX_A LIB_XEREC_A \
		LIB_XECVA_BIN_SIMU_VENC_A LIB_XECVA_BIN_MUX_PS_A LIB_XECVA_BIN_DEMUX_PS_A LIB_XECVA_PBPSP_A \
		LIB_XECVA_BIN_DISPLAY_V4L2_A LIB_XECVA_BIN_DM646X_CANVAS_A LIB_XECVA_BIN_OSD_A \
		LIB_XECVA_BIN_CODEC_DVSDK_A LIB_XECVA_BIN_COLORBAR_A LIB_XEALGORITHM_A LIB_XECVA_BIN_DEMUX_H264_A\
		LIB_XECVA_BIN_DM646X_PCI_E_A LIB_XECVA_BIN_DM646X_VPIF_E_A LIB_XECVA_BIN_AUDIO_PLAYBACK_A \
		LIB_XECVA_BIN_DM646X_RESIZER_A LIB_XECVA_EXT_DM646X_PCI_EXC_A LIB_DSPLINK_LIB \
		LIB_XECVA_BIN_TVP5158_A LIB_XECVA_BIN_DM646X_CCV_A LIB_XECVA_BIN_DM646X_PCI2_F_A \
		LIB_XECVA_BIN_DEMUX_MP4V_A LIB_XECVA_BIN_DM368_RESIZER_A LIB_XECVA_BIN_CAPTURE_V4L2_A \
		LIB_XECVA_BIN_Joint_4xD1_A LIB_XECVA_BIN_DM646X_GUI_A LIB_XECVA_BIN_CUTTER_PS_A \
		LIB_XECVA_BIN_CAPTURE_AUDIO_A LIB_XECVA_BIN_ALSA_PLAYBACK_A LIB_XECVA_BIN_CODEC_FFMPEG_A \
		LIB_XECVA_BIN_EXCLUSIVE_ORDER_A

###############################################################################
ifeq ($(TARGET_PRODUCT_MODEL),RB-NG)

BASE_DIR_y := $(TOPDIR)/base/libxeSAP
BASE_DIR_y += $(TOPDIR)/base/libxeLOG
BASE_DIR_y += $(TOPDIR)/base/libxeSOE
BASE_DIR_y += $(TOPDIR)/base/libxeAA
BASE_DIR_y += $(TOPDIR)/base/libxeCEO
BASE_DIR_y += $(TOPDIR)/base/libxePTZ
BASE_DIR_y += $(TOPDIR)/base/libxeWDG
BASE_DIR_y += $(TOPDIR)/base/libxeAC51
BASE_DIR_y += $(TOPDIR)/base/libxeCVA
BASE_DIR_y += $(TOPDIR)/base/libxeDEX
BASE_DIR_y += $(TOPDIR)/base/libxeRecording

LDFLAGS += -L$(LIBDIR)
LDFLAGS += -Wl,--start-group
LDFLAGS += $(LIBDIR)/$(LIB_COMMON_A)
LDFLAGS += $(LIBDIR)/$(LIB_XESAP_A)
LDFLAGS += $(LIBDIR)/$(LIB_XELOG_A)
LDFLAGS += $(LIBDIR)/$(LIB_XESOE_A)
LDFLAGS += $(LIBDIR)/$(LIB_XEAA_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECEO_A)
LDFLAGS += $(LIBDIR)/$(LIB_XEPTZ_A)
LDFLAGS += $(LIBDIR)/$(LIB_XEWDG_A)
LDFLAGS += $(LIBDIR)/$(LIB_XEAC51_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_A)
LDFLAGS += $(LIBDIR)/$(LIB_XEDEX_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_PBPSP_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_MUX_PS_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_PBPSP_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_MUX_PS_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_OSD_A)

ifeq ($(TARGET_PLATFORM), X86)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_SIMU_VENC_A)
else
LDFLAGS += $(LIBDIR)/$(LIB_DSPLINK_LIB)
LDFLAGS += $(LIBDIR)/$(LIB_XEALGORITHM_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_CODEC_DVSDK_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DISPLAY_V4L2_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DM646X_CANVAS_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_OSD_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DM646X_PCI_E_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DM646X_VPIF_E_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_AUDIO_PLAYBACK_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_CAPTURE_AUDIO_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DM646X_RESIZER_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_EXT_DM646X_PCI_EXC_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DM646X_GUI_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DEMUX_PS_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DEMUX_H264_A)
LDFLAGS += $(LIBDIR)/$(LIB_XECVA_BIN_DEMUX_MP4V_A)
endif

LDFLAGS += -Wl,--end-group
LDFLAGS += -ldl -lm -lc -lrt

endif#TARGET_PRODUCT_MODEL==RB-NG
###############################################################################

export BASE_DIR_y

#add -I CFLAG
CFLAGS += $(addsuffix /include,$(addprefix -I,$(BASE_DIR_y)))
