VERSION_MAJOR := 0
VERSION_MINOR := 1
VERSION_REVISION := 0
VERSION_BUILD_ID := $(shell unset LANG; svn info | sed -n '/^Revision/s/Revision:[[:space:]]*\([[:digit:]]\+\)/\1/p'; )

ifeq  ($(VERSION_BUILD_ID),)
VERSION_BUILD_ID := 999
endif

CFLAGS += -DVERSION_MAJOR=$(VERSION_MAJOR)
CFLAGS += -DVERSION_MINOR=$(VERSION_MINOR)
CFLAGS += -DVERSION_REV=$(VERSION_REVISION)
CFLAGS += -DVERSION_BUILD_ID=$(VERSION_BUILD_ID)

export VERSION_MAJOR VERSION_MINOR VERSION_REVISION VERSION_BUILD_ID

